-- Generated by matugen — do not edit manually
local M = {}
M.primary           = "ffb783"
M.on_primary        = "4f2500"
M.surface           = "19120d"
M.outline           = "9f8d83"
M.outline_variant   = "52443b"
M.error             = "ffb4ab"
return M
