# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    blur {
        size       = 5
        brightness = 0.60
        contrast   = 0.75
    }

    shadow {
        range = 15
    }

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

