# Hyprcursor
env = HYPRCURSOR_THEME, Nordzy-hyprcursors

# NVIDIA (Turing+ with GSP firmware)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA screencopy fix — lineal DMA-buf para pipewiresrc bajo NVIDIA+Hyprland
env = AQ_NO_MODIFIERS, 1

# Termfile-chooser
env = GTK_USE_PORTAL, 1
env = QT_QPA_PLATFORMTHEME, xdgdesktopportal
