# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# Obsidian — frosted glass effect
windowrule = tag -default-opacity, match:class obsidian
windowrule = opacity 0.75 0.75, match:class obsidian

# nmtui — float centered
windowrule = float on,    match:class kitty, match:title nmtui
windowrule = size 60% 70%, match:class kitty, match:title nmtui
windowrule = center 1,    match:class kitty, match:title nmtui

# Music scratchpad
windowrule = workspace special:music, match:class org\.omarchy\.ncmpcpp

# Messaging scratchpad
windowrule = workspace special:messaging, match:class chrome-web\.whatsapp\.com__-Default
windowrule = workspace special:messaging, match:class vesktop

