-- Generated by matugen — do not edit manually
local M = {}
M.primary           = "adc6ff"
M.on_primary        = "102f60"
M.surface           = "111318"
M.outline           = "8e9099"
M.outline_variant   = "44474f"
M.error             = "ffb4ab"
return M
