# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ./hyprland/animation.conf
source = ./hyprland/bindings.conf
source = ./hyprland/decorations.conf
source = ./hyprland/envs.conf
source = ./hyprland/execs.conf
source = ./hyprland/generals.conf
source = ./hyprland/input.conf
source = ./hyprland/layouts.conf
source = ./hyprland/looknfeel.conf
source = ./monitors.conf
source = ./hyprland/rules.conf
source = ./hyprland/workspaces.conf
source = ./hyprland/xwaylands.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
