#!/usr/bin/env bash
# Runs after matugen generates all templates.
# Reloads themed apps so changes take effect without restarting anything.

KITTY_THEME="$HOME/.config/kitty/matugen-theme.conf"

# ── Kitty — live reload via socket ───────────────────────────────────────────
if [[ -f "$KITTY_THEME" ]]; then
    for sock in /tmp/kitty-*; do
        [[ "$sock" =~ ^/tmp/kitty-[0-9]+$ ]] || continue
        kitten @ --to "unix:$sock" set-colors --all "$KITTY_THEME" 2>/dev/null || true
    done
fi

# ── btop — theme reload via SIGUSR2 ──────────────────────────────────────────
killall -USR2 btop 2>/dev/null || true

# ── Hyprland — reload config (picks up new colors.lua) ───────────────────────
hyprctl reload 2>/dev/null || true

# ── Zen Browser — copy CSS to active profile chrome/ ─────────────────────────
ZEN_CSS_SRC="$HOME/.config/matugen/output/zen-matugen.css"

if [[ -f "$ZEN_CSS_SRC" ]]; then
    ZEN_PROFILE=$(python3 -c "
import configparser, os
p = configparser.ConfigParser()
p.read(os.path.expanduser('~/.config/zen/profiles.ini'))
# Install section is authoritative for the actual active profile
for s in p.sections():
    if s.startswith('Install'):
        path = p.get(s, 'Default', fallback=None)
        if path:
            print(os.path.expanduser('~/.config/zen/' + path))
            exit()
# Fall back to Default=1 in profile sections
for s in p.sections():
    if p.get(s, 'Default', fallback='0') == '1':
        print(os.path.expanduser('~/.config/zen/' + p[s].get('Path', '')))
        exit()
" 2>/dev/null)

    if [[ -n "$ZEN_PROFILE" && -d "$ZEN_PROFILE" ]]; then
        ZEN_CHROME="$ZEN_PROFILE/chrome"
        mkdir -p "$ZEN_CHROME"
        cp "$ZEN_CSS_SRC" "$ZEN_CHROME/zen-matugen.css"

        # Create userChrome.css if it doesn't exist or doesn't import zen-matugen.css
        UC="$ZEN_CHROME/userChrome.css"
        if [[ ! -f "$UC" ]] || ! grep -q "zen-matugen.css" "$UC"; then
            cat > "$UC" << 'EOF'
@import "zen-matugen.css";
@import "zen-themes.css";

:root {
    --zen-primary-color:      var(--c-surface0) !important;
    --zen-colors-primary:     var(--c-accent) !important;
    --zen-colors-secondary:   var(--c-surface0) !important;
    --zen-colors-tertiary:    var(--c-base) !important;
    --zen-colors-border:      var(--c-surface1) !important;
    --toolbarbutton-icon-fill: var(--c-accent) !important;
    --lwt-text-color:         var(--c-text) !important;
    --arrowpanel-color:       var(--c-text) !important;
    --arrowpanel-background:  var(--c-base) !important;
    --newtab-background-color: var(--c-base) !important;
}
EOF
        fi
    fi
fi

# ── hyprpaper — sync wallpaper (extract first frame if video) ────────────────
WALLPAPER_STATE="$HOME/.local/state/quickshell/wallpaper.txt"
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"

if [[ -f "$WALLPAPER_STATE" ]]; then
    HP_SRC=$(cat "$WALLPAPER_STATE")

    if [[ -f "$HP_SRC" ]]; then
        HP_EXT="${HP_SRC##*.}"
        HP_EXT="${HP_EXT,,}"

        case "$HP_EXT" in
            mp4|mkv|webm|gif|mov|avi)
                HP_WALL="$HOME/.local/state/quickshell/hyprpaper-frame.jpg"
                ffmpeg -ss 0.0 -i "$HP_SRC" -vframes 1 -q:v 2 "$HP_WALL" -y 2>/dev/null
                ;;
            *)
                HP_WALL="$HP_SRC"
                ;;
        esac

        if [[ -f "$HP_WALL" ]]; then
            cat > "$HYPRPAPER_CONF" << EOF
preload = $HP_WALL

wallpaper  {
	monitor =
	path = $HP_WALL
	fit_mode = cover
}

splash = false
EOF
            # No restart: Quickshell is running and layer-shell stacks surfaces by map order
            # (last mapped = on top). Restarting hyprpaper here would put it above Quickshell's
            # background, hiding video wallpapers. Config update is enough — hyprpaper reads it
            # on next boot (before Quickshell maps its surfaces).
        fi
    fi
fi

# ── SDDM silent theme — sync wallpaper + matugen colors ──────────────────────
WALLPAPER_STATE="$HOME/.local/state/quickshell/wallpaper.txt"
COLORS_JSON="$HOME/.config/matugen/colors.json"

if [[ -f "$WALLPAPER_STATE" && -f "$COLORS_JSON" ]] && command -v python3 &>/dev/null; then
    WALLPAPER_PATH=$(cat "$WALLPAPER_STATE")

    if [[ -f "$WALLPAPER_PATH" ]]; then
        EXT="${WALLPAPER_PATH##*.}"
        EXT="${EXT,,}"
        DEST_NAME="qs-current.$EXT"

        PRIMARY=$(python3 -c "import json; d=json.load(open('$COLORS_JSON')); print(d['colors']['primary']['hex'])" 2>/dev/null)
        ON_PRIMARY=$(python3 -c "import json; d=json.load(open('$COLORS_JSON')); print(d['colors']['on_primary']['hex'])" 2>/dev/null)

        if [[ "$PRIMARY" != "null" && -n "$PRIMARY" ]]; then
            cat > /tmp/sddm-custom.conf << EOF
; Generated by Quickshell matugen post-hook — do not edit manually
; Primary: ${PRIMARY} | Wallpaper: ${DEST_NAME}

[General]
scale = 1.0
enable-animations = true
animated-background-placeholder = "arch.png"
background-fill-mode = "fill"

[LockScreen]
display = true
padding-top = 0
padding-right = 0
padding-bottom = 0
padding-left = 0
background = "${DEST_NAME}"
use-background-color = false
background-color = "#000000"
blur = 0
brightness = -0.1
saturation = 0.0

[LockScreen.Clock]
display = true
position = "center-right"
align = "center"
format = "hh:mm"
font-family = "RedHatDisplay"
font-size = 120
font-weight = 900
color = "#FFFFFF"

[LockScreen.Date]
display = true
format = "dddd, MMMM dd, yyyy"
locale = "en_US"
font-family = "RedHatDisplay"
font-size = 25
font-weight = 750
color = "${PRIMARY}"
margin-top = -15

[LockScreen.Message]
display = false
position = "bottom-center"
align = "center"
text = "Press any key"
font-family = "RedHatDisplay"
font-size = 12
font-weight = 400
display-icon = true
icon = "enter.svg"
icon-size = 16
color = "#FFFFFF"
paint-icon = true
spacing = 0

[LoginScreen]
background = "${DEST_NAME}"
use-background-color = false
background-color = "#000000"
blur = 0
brightness = 0.0
saturation = 0.0

[LoginScreen.LoginArea]
position = "right"
margin = 50

[LoginScreen.LoginArea.Avatar]
shape = "circle"
border-radius = 30
active-size = 120
inactive-size = 80
inactive-opacity = 0.5
active-border-size = 0
inactive-border-size = 0
active-border-color = "${PRIMARY}"
inactive-border-color = "${PRIMARY}"
always-active = false

[LoginScreen.LoginArea.Username]
font-family = "RedHatDisplay"
font-size = 18
font-weight = 700
color = "#FFFFFF"
margin = 10

[LoginScreen.LoginArea.PasswordInput]
width = 150
height = 30
display-icon = false
font-family = "RedHatDisplay"
font-size = 12
icon = "password.svg"
icon-size = 16
content-color = "#000000"
background-color = "#FFFFFF"
background-opacity = 1.0
border-size = 0
border-color = "${PRIMARY}"
border-radius-left = 15
border-radius-right = 0
margin-top = 10
masked-character = "●"

[LoginScreen.LoginArea.LoginButton]
background-color = "${PRIMARY}"
background-opacity = 1.0
active-background-color = "${PRIMARY}"
active-background-opacity = 0.85
icon = "arrow-right.svg"
icon-size = 18
content-color = "${ON_PRIMARY}"
active-content-color = "${ON_PRIMARY}"
border-size = 0
border-color = "${PRIMARY}"
border-radius-left = 0
border-radius-right = 15
margin-left = 0
show-text-if-no-password = true
hide-if-not-needed = false
font-family = "RedHatDisplay"
font-size = 12
font-weight = 600

[LoginScreen.LoginArea.Spinner]
display-text = true
text = "Logging in"
font-family = "RedHatDisplay"
font-weight = 600
font-size = 14
icon-size = 30
icon = "spinner.svg"
color = "#FFFFFF"
spacing = 5

[LoginScreen.LoginArea.WarningMessage]
font-family = "RedHatDisplay"
font-size = 11
font-weight = 400
normal-color = "#FFFFFF"
warning-color = "#FFA500"
error-color = "#FF6B6B"
margin-top = 10

[LoginScreen.MenuArea.Buttons]
margin-top = 50
margin-right = 50
margin-bottom = 50
margin-left = 0
size = 30
border-radius = 15
spacing = 10
font-family = "RedHatDisplay"

[LoginScreen.MenuArea.Popups]
max-height = 300
item-height = 30
item-spacing = 2
padding = 5
display-scrollbar = true
margin = 5
background-color = "#FFFFFF"
background-opacity = 1.0
active-option-background-color = "#F1F1F1"
active-option-background-opacity = 1.0
content-color = "#000000"
active-content-color = "${PRIMARY}"
font-family = "RedHatDisplay"
border-size = 0
border-color = "${PRIMARY}"
font-size = 11
icon-size = 16

[LoginScreen.MenuArea.Session]
display = true
position = "bottom-right"
index = 1
popup-direction = "up"
popup-align = "center"
display-session-name = false
button-width = -1
popup-width = 200
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 1.0
content-color = "#FFFFFF"
active-content-color = "#000000"
border-size = 0
font-size = 10
icon-size = 16

[LoginScreen.MenuArea.Layout]
display = true
position = "bottom-right"
index = 2
popup-direction = "up"
popup-align = "center"
popup-width = 180
display-layout-name = false
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 1.0
content-color = "#FFFFFF"
active-content-color = "#000000"
border-size = 0
font-size = 10
icon = "language.svg"
icon-size = 16

[LoginScreen.MenuArea.Keyboard]
display = true
position = "bottom-right"
index = 3
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 1.0
content-color = "#FFFFFF"
active-content-color = "#000000"
border-size = 0
icon = "keyboard.svg"
icon-size = 16

[LoginScreen.MenuArea.Power]
display = true
position = "bottom-right"
index = 4
popup-direction = "up"
popup-align = "center"
popup-width = 100
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 1.0
content-color = "#FFFFFF"
active-content-color = "#000000"
border-size = 0
icon = "power.svg"
icon-size = 16

[LoginScreen.VirtualKeyboard]
scale = 1.0
position = "login"
start-hidden = true
background-color = "#FFFFFF"
background-opacity = 1.0
key-content-color = "#000000"
key-color = "#F1F1F1"
key-opacity = 1.0
key-active-background-color = "#F1F1F1"
key-active-opacity = 1.0
selection-background-color = "#000000"
selection-content-color = "#FFFFFF"
primary-color = "${PRIMARY}"
border-size = 0
border-color = "${PRIMARY}"
restrict-input = "none"

[Tooltips]
enable = true
font-family = "RedHatDisplay"
font-size = 11
content-color = "#000000"
background-color = "#FFFFFF"
background-opacity = 1.0
border-radius = 5
disable-user = false
disable-login-button = true
EOF

            sudo /usr/local/bin/sddm-theme-sync \
                "$WALLPAPER_PATH" "$DEST_NAME" /tmp/sddm-custom.conf 2>/dev/null || true
        fi
    fi
fi
