$monitor = ~/.config/hypr/monitors.conf
$animation = ~/.config/caelestia/hyprland/animation.conf

# Colors
$surfaced1 = 0f0f0fff
$surfaced2 = 050505ff

# Apps
$terminal = kitty
$browser = zen-browser
$editor = nvim
$fileExplorer = kitty yazi

# Touchpad
$touchpadScrollFactor = 1.0

# Blur
$blurSize = 5
$blurPasses = 2
$blurXray = false
$blurNoise = 0.0

# Shadow
$shadowRange = 30
$shadowColour = rgba($surfaced1)
$shadowColourInactive = rgba($surfaced2)

# Window styling
$windowRounding = 0

# Misc
$cursorTheme = Nordzy-cursors
$cursorSize = 24

# ### Keybinds ###
# Apps
$kbTerminal = Super, Return
$kbBrowser = Super, B
$kbEditor = Super, C
$kbFileExplorer = Super, E
