#!/usr/bin/env bash
SCHEME="$HOME/.local/share/caelestia/hypr/scheme/current.conf"
OUT="$HOME/.config/zen/n9raehyd.deadlock/chrome/zen-caelestia.css"

get_color() {
    grep "^\$$1 = " "$SCHEME" | awk '{print $3}'
}

cat > "$OUT" << EOF
/* Generated by caelestia - do not edit manually */
:root {
    --c-accent:   #$(get_color primary);
    --c-text:     #$(get_color text);
    --c-mantle:   #$(get_color mantle);
    --c-base:     #$(get_color base);
    --c-surface0: #$(get_color surface0);
    --c-surface1: #$(get_color surface1);
}
EOF
