-- Generated by nwg-displays on 2026-07-10 at 16:21:41. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.2000000000000002
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1600x0",
    scale = 1.2000000000000002
})
