-- Generated by matugen — do not edit manually
local M = {}
M.primary           = "{{colors.primary.default.hex_stripped}}"
M.on_primary        = "{{colors.on_primary.default.hex_stripped}}"
M.surface           = "{{colors.surface.default.hex_stripped}}"
M.outline           = "{{colors.outline.default.hex_stripped}}"
M.outline_variant   = "{{colors.outline_variant.default.hex_stripped}}"
M.error             = "{{colors.error.default.hex_stripped}}"
return M
