# Configuracion para anydesk
windowrulev2 = float, class:^(anydesk)$
windowrulev2 = center, class:^(anydesk)$
windowrulev2 = size 1280 720, class:^(anydesk)$
windowrulev2 = stayfocused, class:^(anydesk)$
