general {
    lock_cmd         = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd  = hyprctl dispatch dpms on
}

# Dim screen after 3 min
listener {
    timeout   = 180
    on-timeout = brightnessctl -s set 20
    on-resume  = brightnessctl -r
}

# Lock screen after 5 min
listener {
    timeout   = 300
    on-timeout = pidof hyprlock || hyprlock
}

# Turn off screen after 6 min
listener {
    timeout   = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on && brightnessctl -r
}
