general {
    ignore_empty_input = true
}

background {
    monitor =
    path    = ~/Pictures/Wallpapers/elden_ring_giant_moon.png
    blur_passes  = 3
    blur_size    = 8
    brightness   = 0.5
}

input-field {
    monitor  =
    size     = 220, 50
    position = 0, -80

    outline_thickness = 2
    dots_size         = 0.3
    dots_spacing      = 0.2
    dots_center       = true
    rounding          = 8

    outer_color  = rgb(cccccc)
    inner_color  = rgba(05050580)
    font_color   = rgb(ffffff)
    font_family  = Iosevka Term Nerd Font

    placeholder_text = <i>password</i>
    fail_text        = <i>wrong ($ATTEMPTS)</i>
    fade_on_empty    = true

    halign = center
    valign = center
}

# Clock
label {
    monitor     =
    text        = cmd[update:1000] echo "$TIME"
    font_size   = 64
    font_family = Iosevka Term Nerd Font

    position = 0, 100
    halign   = center
    valign   = center
}

# Date
label {
    monitor     =
    text        = cmd[update:60000] date "+%A, %B %d"
    font_size   = 18
    font_family = Iosevka Term Nerd Font

    position = 0, 30
    halign   = center
    valign   = center
}
