return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	cmd = { "TSInstall", "TSUpdate", "TSBufEnable", "TSBufDisable" },
	opts = {
		ensure_installed = {
			-- Languages you use
			"lua",
			"javascript",
			"typescript",
			"tsx",
			"html",
			"css",
			"scss",
			"json",
			"yaml",
			"graphql",
			"svelte",
			"go",
			"gomod",
			"gosum",
			"python",
			"c",
			"cpp",
			"c_sharp",
			"bash",
			"markdown",
			"markdown_inline",
			"latex",
			-- Utility
			"vim",
			"vimdoc",
			"regex",
			"query",
			"diff",
			"gitcommit",
			"git_rebase",
			"yuck",
		},
	},
}
