##################################
# WINAPPS CONFIGURATION FILE
##################################

WAFLAVOR="libvirt"
VM_NAME="WinApps"
RDP_IP="192.168.122.100"
RDP_USER="Deadlock"
RDP_PASS="remote51"
RDP_FLAGS="/cert:ignore /drive:home,/home/deadlock /drive:files,/home/deadlock/Files"
REMOVABLE_MEDIA="/home/deadlock/Files"
RDP_SCALE=100
MULTIMON="false"
DEBUG="false"
AUTOPAUSE="on"
AUTOPAUSE_TIME=60
